version: "3.9"

services:
  calendar_test:
    container_name: calendar_test
    build:
      context: ..
      dockerfile: build/Dockerfile.testing
    command:
      - --service=calendar:6703
      - --events-db=postgres://${CALENDAR_PG_USER}:${CALENDAR_PG_PASSWORD}@postgres:5432/${CALENDAR_PG_DB_NAME}
      - --migrations-dir=/migrations
      - --rmq-uri=amqp://${CALENDAR_RMQ_USER}:${CALENDAR_RMQ_PASSWORD}@rmq:5672
      - --queue=${CALENDAR_SENT_NOTIFICATIONS_RMQ_QUEUE}
    depends_on:
      - calendar
      - scheduler
      - sender
    volumes:
      - ../migrations:/migrations:ro
    networks:
      - default

  calendar:
    container_name: calendar
    build:
      context: ..
      dockerfile: build/Dockerfile.calendar
    volumes:
      - ../configs:/etc/calendar:ro
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy

  scheduler:
    container_name: calendar_scheduler
    build:
      context: ..
      dockerfile: build/Dockerfile.scheduler
    volumes:
      - ../configs:/etc/calendar:ro
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy
      rmq:
        condition: service_healthy

  sender:
    container_name: calendar_sender
    build:
      context: ..
      dockerfile: build/Dockerfile.sender
    volumes:
      - ../configs:/etc/calendar:ro
    networks:
      - default
    depends_on:
      rmq:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${CALENDAR_PG_USER}
      POSTGRES_PASSWORD: ${CALENDAR_PG_PASSWORD}
      POSTGRES_DB: ${CALENDAR_PG_DB_NAME}
    networks:
      - default
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 3s
      retries: 5

  rmq:
    container_name: "rmq"
    restart: always
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${CALENDAR_RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${CALENDAR_RMQ_PASSWORD}
    networks:
      - default
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  default:
    name: calendar_test_network
