version: "3.9"

services:
  calendar_test:
    container_name: calendar_test
    build:
      context: ..
      dockerfile: build/Dockerfile.testing
    command:
      - --service=calendar:6703
      - --events-db=postgres://${CALENDAR_PG_USER}:${CALENDAR_PG_PASSWORD}@postgres:5432/${CALENDAR_PG_DB_NAME}
      - --rmq-uri=amqp://${CALENDAR_RMQ_USER}:${CALENDAR_RMQ_PASSWORD}@rmq:5672
      - --queue=${CALENDAR_SENT_NOTIFICATIONS_RMQ_QUEUE}
    depends_on:
      - calendar
      - scheduler
      - sender
    volumes:
      - ../migrations:/migrations:ro
    networks:
      - default

  calendar:
    restart: on-failure
    container_name: calendar
    build:
      context: ..
      dockerfile: build/Dockerfile.calendar
    volumes:
      - ../configs:/etc/calendar:ro
    networks:
      - default
    depends_on:
      migrator:
        condition: service_started

  scheduler:
    restart: on-failure
    container_name: calendar_scheduler
    build:
      context: ..
      dockerfile: build/Dockerfile.scheduler
    volumes:
      - ../configs:/etc/calendar:ro
    networks:
      - default
    depends_on:
      migrator:
        condition: service_started
      rmq:
        condition: service_healthy

  sender:
    restart: on-failure
    container_name: calendar_sender
    build:
      context: ..
      dockerfile: build/Dockerfile.sender
    volumes:
      - ../configs:/etc/calendar:ro
    networks:
      - default
    depends_on:
      rmq:
        condition: service_healthy

  migrator:
    container_name: migrator
    build:
      context: ..
      dockerfile: build/Dockerfile.migrator.testing
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${CALENDAR_PG_USER}:${CALENDAR_PG_PASSWORD}@postgres:5432/${CALENDAR_PG_DB_NAME}
    command:
      - --dir=/migrations
      - up
    volumes:
      - ../migrations:/migrations:ro
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    restart: on-failure
    image: postgres
    environment:
      POSTGRES_USER: ${CALENDAR_PG_USER}
      POSTGRES_PASSWORD: ${CALENDAR_PG_PASSWORD}
      POSTGRES_DB: ${CALENDAR_PG_DB_NAME}
    networks:
      - default
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 3s
      retries: 5

  rmq:
    restart: on-failure
    container_name: "rmq"
    image: rabbitmq:3.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${CALENDAR_RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${CALENDAR_RMQ_PASSWORD}
    networks:
      - default
    healthcheck:
      test: rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  default:
    name: calendar_test_network
