logger:
  level: debug
  pretty: true

storage:
  type: sql
  db:
    host: postgres
    port: 5432
    database: calendar
    user: user
    password: password123

http:
  host: 0.0.0.0
  port: 8080

grpc:
  host: 0.0.0.0
  port: 6703
