logger:
  level: debug
  pretty: true

storage:
  type: sql
  db:
    host: localhost
    port: 6543
    database: test
    user: postgres
    password: password123

rmq:
  scheme: amqp
  host: localhost
  port: 5672
  user: user
  password: password123
  queue: "event_notifications"

tick: 5s
