logger:
  level: debug
  pretty: true

storage:
  type: sql
  db:
    host: postgres
    port: 5432
    database: calendar
    user: user
    password: password123

rmq:
  scheme: amqp
  host: rmq
  port: 5672
  user: user
  password: password123
  queue: "event_notifications"

tick: 100ms
